version: '3.8'

services:
  app:
    build: .
    container_name: todo_app
    ports:
      - "8080:8080"
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=todoapp
      - DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
